### ISSUE TITLE
Crashes due to missing credentials.json file

### ISSUE THREAD

**Issue by ftrotter** [sVathis/gContacts2logseq#1]
On the first out-of-the-box run of the script, it crashes because credentials.json is missing. 

Specifically: 

Fmbpro:gContacts2logseq ftrotter$ python gContacts2logseq.py
Traceback (most recent call last):
  File "/Users/ftrotter/gitper/gContacts2logseq/gContacts2logseq.py", line 194, in <module>
    creds = login()
            ^^^^^^^
  File "/Users/ftrotter/gitper/gContacts2logseq/gContacts2logseq.py", line 173, in login
    flow = InstalledAppFlow.from_client_secrets_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/google_auth_oauthlib/flow.py", line 180, in from_client_secrets_file
    with open(client_secrets_file, 'r') as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

**Comment by quinn-p-mchugh** [comment]
Hey @ftrotter,

I resolved this by following these instructions on [setting up authorizing credentials for a desktop application](https://developers.google.com/people/quickstart/python#authorize_credentials_for_a_desktop_application).

Google will prompt you to download a file called `client_secret_1212133143141.json` or similar. I renamed this file to `credentials.json` and added it to the same directory as `gContacts2logseq.py`.

But yeah, I agree - directions could be made clearer.
